### ISSUE TITLE
action  sets

### ISSUE THREAD

**Issue by kevgo** [contest-framework/roadmap#6]
Removed from the Rust implementation for now, add back if needed:

### Multiple action sets

_(coming soon)_

Tertestrial allows to define several sets of actions and switch between them at
runtime. An example is to have one action set for running tests using a real
browser and another action set to run them using a faster headless browser.

**tertestrial.yml**

```yml
actions:
  headless:
    - match:
        filename: '\.feature$'
      command: "TEST_PLATFORM=headless cucumber-js {{filename}}"

    - match:
        filename: '\.feature$'
        line: '\d+'
      command: "TEST_PLATFORM=headless cucumber-js {{filename}}:{{line}}"

  firefox:
    - match:
        filename: '\.feature$'
      command: "TEST_PLATFORM=firefox cucumber-js {{filename}}"

    - match:
        filename: '\.feature$'
        line: '\d+'
      command: "TEST_PLATFORM=firefox cucumber-js {{filename}}:{{line}}"
```

When Tertestrial starts, in activates the first action set. In this example, it
means if you tell it to test a file, it will do so using the headless browser.
When you switch to the second action set, it well test files using Firefox as
the browser.
